# Generated by Django 4.0.4 on 2022-06-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='registrarion_date',
            field=models.DateTimeField(default='2022-06-21 14:17:28', verbose_name='Дата регистрации'),
        ),
    ]
