# Generated by Django 4.0.4 on 2022-06-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_registrarion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='registrarion_date',
            field=models.DateTimeField(default='08-06-2022 09:05:02', verbose_name='Дата регистрации'),
        ),
    ]
