# Generated by Django 4.0.4 on 2022-08-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='composition_dish',
            field=models.TextField(verbose_name='Состав блюда'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description_dish',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name_dish',
            field=models.CharField(max_length=255, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='section_menu',
            field=models.CharField(choices=[('economy', 'эконом'), ('optimal', 'оптимальный'), ('business', 'бизнес')], max_length=14, verbose_name='Раздел меню'),
        ),
    ]
