# Generated by Django 4.0.4 on 2022-04-28 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confectionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название кондитерской')),
                ('description_confectionary', models.TextField(verbose_name='Описание')),
                ('link_img_confectionary', models.URLField(verbose_name='Ссылка на фото кондитерской')),
                ('city', models.CharField(max_length=100, verbose_name='Город расположения')),
                ('city_area', models.CharField(max_length=100, verbose_name='Район города')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(max_length=20, verbose_name='Дом')),
                ('office', models.CharField(blank=True, max_length=20, null=True, verbose_name='Офис')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dish', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('price_dish', models.IntegerField(max_length=7, verbose_name='Цена блюда')),
                ('description_dish', models.CharField(max_length=500, verbose_name='Комментарий к блюду')),
                ('link_img_dish', models.URLField(verbose_name='Ссылка на фото блюда')),
                ('name_confectionary', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_confectionary', to='confectionary.confectionary')),
            ],
            options={
                'ordering': ['price_dish'],
            },
        ),
        migrations.CreateModel(
            name='ImgFileMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_dish', models.ImageField(blank=True, null=True, upload_to='img_dish/', verbose_name='Фото блюда')),
                ('file_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_menu', to='confectionary.menu')),
            ],
        ),
        migrations.CreateModel(
            name='ImgFileConfectionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_confectionary', models.ImageField(blank=True, null=True, upload_to='img_confectionary/', verbose_name='Фото кондитерской')),
                ('file_confectionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_confectionary', to='confectionary.confectionary')),
            ],
        ),
    ]
