# Generated by Django 4.0.4 on 2022-05-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confectionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('confectionary_name', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=100, unique=True, verbose_name='Название кондитерской')),
                ('number_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер телефона кондитерской')),
                ('description_confectionary', models.TextField(blank=True, verbose_name='Описание')),
                ('address_ward', models.TextField(default='', verbose_name='Адрес кондитерской')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dish', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('price_dish', models.IntegerField(verbose_name='Цена блюда')),
                ('description_dish', models.CharField(max_length=500, verbose_name='Описание')),
                ('name_confectionary', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_confectionary', to='confectionary.confectionary')),
            ],
            options={
                'ordering': ['price_dish'],
            },
        ),
        migrations.CreateModel(
            name='ImgFileMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_dish', models.ImageField(blank=True, null=True, upload_to='img_dish/', verbose_name='Фото блюда')),
                ('file_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_menu', to='confectionary.menu')),
            ],
        ),
        migrations.CreateModel(
            name='ImgFileConfectionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_confectionary', models.ImageField(blank=True, null=True, upload_to='img_confectionary/', verbose_name='Фото кондитерской')),
                ('file_confectionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_confectionary', to='confectionary.confectionary')),
            ],
        ),
    ]
