# Generated by Django 4.0.4 on 2022-05-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confectionary', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confectionary',
            name='password',
        ),
    ]
