# Generated by Django 4.0.4 on 2022-08-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confectionary', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confectionary',
            name='avatar_confectionary',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_confectionary/', verbose_name='Аватар кондитерской'),
        ),
    ]
