# Generated by Django 4.0.4 on 2022-05-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confectionary', '0003_remove_confectionary_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='confectionary',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пароль'),
        ),
    ]
