# Generated by Django 4.0.4 on 2022-08-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_menu', models.IntegerField(default=1, verbose_name='Количество блюд')),
                ('order_status', models.CharField(choices=[('generated', 'создан'), ('paid_for', 'оплачен'), ('formed', 'сформирован'), ('desire_ward', 'желание подопечного'), ('admitted', 'принят'), ('completed', 'выполнен'), ('archive', 'архивный')], default='generated', max_length=200, verbose_name='Статус заказа')),
                ('price_order', models.IntegerField(default=0, verbose_name='Цена заказа')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Содержимое корзины',
            },
        ),
        migrations.CreateModel(
            name='OrderExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status_execution', models.CharField(choices=[('generated', 'создан'), ('paid_for', 'оплачен'), ('formed', 'сформирован'), ('desire_ward', 'желание подопечного'), ('admitted', 'принят'), ('completed', 'выполнен'), ('archive', 'архивный')], default='paid_for', max_length=200, verbose_name='Статус заказа')),
                ('order_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_execution', to='business.order')),
            ],
        ),
    ]
