# Generated by Django 4.0.4 on 2022-07-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('menu', '0001_initial'),
        ('confectionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishesward',
            name='confectionary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confectionary', to='confectionary.confectionary'),
        ),
        migrations.AddField(
            model_name='wishesward',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='menu.menu'),
        ),
    ]
