# Generated by Django 4.0.4 on 2022-08-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_orderexecution_remove_wishesward_confectionary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderexecution',
            old_name='order',
            new_name='order_execution',
        ),
        migrations.AlterField(
            model_name='orderexecution',
            name='order_status',
            field=models.CharField(choices=[('generated', 'создан'), ('paid_for', 'оплачен'), ('formed', 'сформирован'), ('desire_ward', 'желание подопечного'), ('admitted', 'принят'), ('completed', 'выполнен'), ('archive', 'архивный')], default='paid_for', max_length=200, verbose_name='Статус заказа'),
        ),
    ]
