# Generated by Django 4.0.4 on 2022-06-21 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confectionary', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default='2022-06-21 14:20:25', verbose_name='Дата создания корзины'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_confectioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_confectioner', to='confectionary.confectionary'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_philantropist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_philantropist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ward', to=settings.AUTH_USER_MODEL),
        ),
    ]
