# Generated by Django 4.0.4 on 2022-06-21 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confectionary', '0002_initial'),
        ('business', '0005_alter_order_order_date_alter_order_user_confectioner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Содержимое корзины'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default='2022-06-21 14:22:23', verbose_name='Дата создания корзины'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_confectioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_confectioner', to='confectionary.confectionary'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_philantropist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_philantropist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ward', to=settings.AUTH_USER_MODEL),
        ),
    ]
