# Generated by Django 4.0.4 on 2022-08-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_rename_order_orderexecution_order_execution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderexecution',
            old_name='order_status',
            new_name='order_status_execution',
        ),
    ]
