# Generated by Django 4.0.4 on 2022-06-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_order_options_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_confectioner',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_philantropist',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_ward',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default='2022-06-21 14:24:47', verbose_name='Дата создания корзины'),
        ),
    ]
