# Generated by Django 4.0.4 on 2022-06-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_remove_order_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
