# Generated by Django 4.0.4 on 2022-06-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_remove_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default='2022-06-21 14:28:02', verbose_name='Дата создания корзины'),
        ),
    ]
