# Generated by Django 4.0.4 on 2022-06-21 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confectionary', '0002_initial'),
        ('business', '0009_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('generated', 'generated'), ('paid_for', 'paid_for'), ('admitted', 'admitted'), ('completed', 'completed'), ('archive', 'archive')], default=0, max_length=200, verbose_name='Статус заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_confectioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_confectioner', to='confectionary.confectionary'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_philantropist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_philantropist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user_ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ward', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания корзины'),
        ),
    ]
