# Generated by Django 4.0.4 on 2022-06-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('business', '0010_order_order_status_order_user_confectioner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.menu'),
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
