# Generated by Django 4.0.4 on 2022-06-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_order_product_delete_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_confectioner',
            new_name='confectionary',
        ),
    ]
