# Generated by Django 4.0.4 on 2022-06-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_remove_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='confectionary',
            new_name='confectionary_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_philantropist',
            new_name='user_philantropist_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_ward',
            new_name='user_ward_id',
        ),
    ]
