# Generated by Django 4.0.4 on 2022-06-22 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0014_rename_confectionary_order_confectionary_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('generated', 'generated'), ('paid_for', 'paid_for'), ('admitted', 'admitted'), ('completed', 'completed'), ('archive', 'archive')], default='generated', max_length=200, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='WishesWard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_menu', models.IntegerField(verbose_name='Количество блюд')),
                ('order_status', models.CharField(choices=[('generated', 'generated'), ('paid_for', 'paid_for'), ('admitted', 'admitted'), ('completed', 'completed'), ('archive', 'archive')], default='generated', max_length=200, verbose_name='Статус заказа')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_id', to='menu.menu')),
                ('ward_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_philantropist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_philantropist_id', to=settings.AUTH_USER_MODEL)),
                ('wishes_ward_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishes_ward_id', to='business.wishesward')),
            ],
        ),
    ]
