# Generated by Django 4.0.4 on 2022-06-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confectionary', '0002_initial'),
        ('business', '0015_alter_order_order_status_wishesward_ordertaken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertaken',
            options={'verbose_name': 'Взятые заказы', 'verbose_name_plural': 'Взятые заказы'},
        ),
        migrations.AlterModelOptions(
            name='wishesward',
            options={'verbose_name': 'Желания', 'verbose_name_plural': 'Желание подопечного'},
        ),
        migrations.RenameField(
            model_name='wishesward',
            old_name='count_menu',
            new_name='count_product',
        ),
        migrations.AddField(
            model_name='wishesward',
            name='confectionary_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confectionary_id', to='confectionary.confectionary'),
        ),
    ]
