# Generated by Django 4.0.4 on 2022-06-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_remove_wishesward_confectionary_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishesward',
            name='order_status',
        ),
        migrations.AddField(
            model_name='ordertaken',
            name='order_status',
            field=models.CharField(choices=[('generated', 'generated'), ('admitted', 'admitted'), ('paid_for', 'paid_for'), ('completed', 'completed'), ('archive', 'archive')], default='generated', max_length=200, verbose_name='Статус заказа'),
        ),
    ]
