# Generated by Django 4.0.4 on 2022-06-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_alter_wishesward_count_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishesward',
            name='order_wishes',
            field=models.CharField(choices=[('posted', 'posted'), ('taken', 'taken')], default='posted', max_length=200, verbose_name='Статус заказа'),
        ),
    ]
