# Generated by Django 4.0.4 on 2022-04-28 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_user_img', models.ImageField(blank=True, upload_to='avatar_philantropist/', verbose_name='Аватар профиля')),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='avatar_user_img',
        ),
        migrations.AddField(
            model_name='userdata',
            name='link_user_img',
            field=models.URLField(blank=True, verbose_name='Ссылка на аватарку профиля'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='size_donations',
            field=models.IntegerField(default=0, max_length=20, verbose_name='Размер пожертвований'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='status',
            field=models.CharField(choices=[('philantropist', 'philantropist'), ('ward', 'ward'), ('confectioner', 'confectioner')], max_length=14, verbose_name='Статус пользователя'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AddField(
            model_name='avataruser',
            name='model_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
