# Generated by Django 4.0.4 on 2022-08-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_avataruser_fileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='status',
            field=models.CharField(choices=[('philantropist', 'благотворитель'), ('ward', 'подопечный'), ('confectioner', 'кондитер')], max_length=14, verbose_name='Статус пользователя'),
        ),
    ]
