# Generated by Django 4.0.4 on 2022-05-05 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_avataruser_model_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avataruser',
            name='model_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_file', to=settings.AUTH_USER_MODEL),
        ),
    ]
